backend:
  name: git-gateway
  branch: master

media_folder: static/media
public_folder: /media

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/about.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "AboutPage",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "content", widget: "markdown" }
